#!/bin/bash
#Descriptions:

chosen=$(printf "📴 Power Off\n🔃 Reboot\n💤 Suspend\n🐻 Hibernate\n🚪 Log Out\n🔒 Lock" | rofi -dmenu -i -theme-str '@import "/home/agung/.config/rofi/box/powermenu.rasi"')

case "$chosen" in
	"📴 Power Off") poweroff ;;
	"🔃 Reboot") reboot ;;
	"💤 Suspend") systemctl suspend ;;
	"🐻 Hibernate") systemctl hibernate ;;
    "🚪 Log Out") loginctl terminate-user $USER ;;
	"🔒 Lock") swaylock -f -c 000000 ;;
	*) exit 1 ;;
esac

